### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by srimurtisva** [hbons/SparkleShare#1608] opened 2015-01-21 14:36 UTC
What is going wrong?
sms@sms-HP-Mini-210-1000:~$ sparkleshare start
sms@sms-HP-Mini-210-1000:~$ 17:26:30 | Environment | SparkleShare version: 1.4.0, Operating system: Unix (Unix 3.13.0.24)
17:26:30 | Auth | Imported key '/home/sms/.config/sparkleshare/2015-01-21_15h46.key'
17:26:30 | Auth | The following keys may be used:
2048 fa:2c:cb:aa:bc:b0:29:d2:c0:f4:ca:9b:9b:af:10:ac /home/sms/.config/sparkleshare/2015-01-21_15h46.key (RSA)
Marshaling activate signal
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.WebView ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMAttr ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMNode ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMObject ---> System.DllNotFoundException: libwebkitgtksharpglue-1.10.2.so
  at (wrapper managed-to-native) WebKit.DOMObject:webkitsharp_webkit_domobject_get_parentInstance_offset ()
  at WebKit.DOMObject..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.StaticGetterAdapterFrame[GType] (System.Reflection.StaticGetter`1 getter, System.Object obj) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  at GLib.GType.LookupGObjectType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.Object.LookupGType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.GType.op_Explicit (System.Type type) [0x00000] in <filename unknown>:0 
  at WebKit.DOMNode..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.StaticGetterAdapterFrame[GType] (System.Reflection.StaticGetter`1 getter, System.Object obj) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  at GLib.GType.LookupGObjectType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.Object.LookupGType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.GType.op_Explicit (System.Type type) [0x00000] in <filename unknown>:0 
  at WebKit.DOMAttr..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at GtkSharp.WebkitgtkSharp.ObjectManager.Initialize () [0x00000] in <filename unknown>:0 
  at WebKit.WebView..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at SparkleShare.SparkleEventLog..ctor () [0x00000] in <filename unknown>:0 
  at SparkleShare.SparkleUI.ApplicationActivatedDelegate (System.Object sender, System.EventArgs args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <filename unknown>:0 
  at GLib.Signal.ClosureInvokedCB (System.Object o, GLib.ClosureInvokedArgs args) [0x00000] in <filename unknown>:0 
  at GLib.SignalClosure.Invoke (GLib.ClosureInvokedArgs args) [0x00000] in <filename unknown>:0 
  at GLib.SignalClosure.MarshalCallback (IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data) [0x00000] in <filename unknown>:0 
   at GLib.ExceptionManager.RaiseUnhandledException(System.Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.Application.g_application_run(IntPtr , Int32 , IntPtr )
   at GLib.Application.Run(Int32 argc, System.String argv)
   at SparkleShare.SparkleUI.Run()
   at SparkleShare.Program.Main(System.String[] args)

**Comment by hbons** [comment] 2015-01-21 18:09
duplicate of #1606.

**Closed by hbons** 2015-01-21 18:09 UTC
