### ISSUE TITLE
Legacy "action" tray icons do not load properly (default icon does)

### ISSUE THREAD

**Issue by glunardi** [hbons/SparkleShare#1799] opened 2018-01-23 00:50 UTC
### What happened:
Using some GNOME Shell extension in F27 (using Topicons plus right now),
 - The default SparkleShare icon loads properly on startup
 - When a sync is happening (up or down): the icon switches to a failed-to-load image instead of the appropriate icon
 

### What I expected to happen:
 - The SparkleShare tray icon in the bar should update to the right status reporting icon (sync up, sync down, etc, ...)
 - Icon switching works because the Dropbox (is that allowed to be mentioned here?) icon(s) do switch and do the right thing(s)

### This happens when:
 - Syncing up or down on F27 + GNOME + extension to load on top bar

**Comment by glunardi** [comment] 2018-01-23 00:51
Normal (standby icon)
![screenshot from 2018-01-22 19-48-57](https://user-images.githubusercontent.com/1667348/35252267-a3f1fbd2-ffad-11e7-99fd-e01e311ec3d1.png)


Should be an upload icon (syncup)
![screenshot from 2018-01-22 19-47-38](https://user-images.githubusercontent.com/1667348/35252273-a8036634-ffad-11e7-8f0e-402cb9c8ae7d.png)

**Comment by glunardi** [comment] 2018-01-23 01:01
This is using stock GNOME on F27 using the default theme for all:  adwaita

That theme is not supported by default it seems. I tried copying the icons files to where I thought were the right places to no avail. 

Unclear to me whether the `build/icon-theme-installer` script still does the right thing anymore (folders seem to have moved around a bit).

Have not looked at the code yet to see whether it is expecting things in a certain way. Any hints would be great.

**Comment by glunardi** [comment] 2018-01-26 11:51
Update:

For these to work I had to figure out the files locations and running gtk-update-icon-cache.

On F27 with GNOME default themes (on my laptop with my screen config), it is expecting these files here:
 /usr/share/icons/Adwaita/24x24/status/process-syncing-down.png
 /usr/share/icons/Adwaita/24x24/status/process-syncing-error.png
 /usr/share/icons/Adwaita/24x24/status/process-syncing-up.png

`make install` does not create those files. Actually, it does not do anything for Adwaita.

I checked, the files do not exist in /usr/share/icons/hicolor/24x24/status either

There does not seem to be a falback from Adwaita icon theme to any other theme

**Comment by glunardi** [comment] 2018-01-26 22:50
Probably not how it should be fixed but it works for me (TM). 

The same changes should be made to the hicolor Makefile.am because right now it is copying the status icons to what I think is the wrong location(s).

Duplicating those asset files is not great. Maybe there should be one icons folder and a slightly "longer" make file that puts them all in the right places at once using @abock 's 11-year `icon-theme-installer` script :-)

**Comment by hbons** [comment] 2018-02-10 12:29
I'm all for ditching the icon-theme-installer, but I've no clue how to write Makefiles (other than editing them a little :)

**Comment by hbons** [comment] 2018-02-10 19:10
So the status icons installed are in /usr/share/**sparkleshare**/icons/hicolor/status/24x24/. This was the place for app specific icons, but maybe this has changed?

**Comment by glunardi** [comment] 2018-02-10 19:22
The icon cache seems to only pick up icons store in '/usr/share/icons/Adwaita/*' 

Not sure if this has changed. Not sure what native interface is used to resolve icons paths.

The patch above works on my system running F27.

**Comment by hbons** [comment] 2018-02-10 19:41
What about appending a search path? Place `IconTheme.Default.AppendSearchPath ("/usr/share/sparkleshare/icons/hicolor");` before UserInterface.Run();. (sorry I can't test right now my Fedora install is messed up right now).

**Comment by hbons** [comment] 2018-02-11 10:58
So I've installed Fedora to try to reproduce your issues. How did you install hbons/webkit2-sharp? I got  an error trying to build SparkleShare (configure worked fine) because webkit2-sharp.dll can't be find in /usr/lib64.

**Comment by hbons** [comment] 2018-02-11 11:29
Never mind...Looks like there's an rpm for it in F27!

**Comment by glunardi** [comment] 2018-02-11 13:15
Tried to remove all the files I added while testing this (manually).

Will try to test with 'IconTheme.Default.AppendSearchPath' for you now (thank you so much for installing F27 to test also).

I noticed there is a 
`            string icons_path   = IO.Path.Combine (UserInterface.AssetsPath, "icons", "hicolor", "12x12", "status");`
in EventLog.cs for the html content.

**Comment by hbons** [comment] 2018-02-11 16:44
Fix is in https://github.com/hbons/SparkleShare/commit/140db317a7e36dcab2718b12d757d41f52d93e1c. Will merge after the build passes. :)

**Closed** 2018-02-11 16:51 UTC
Labels: GNOME, bug

**Comment by glunardi** [comment] 2018-02-11 17:32
Tested and confirmed as fixed in #1802 (nice solution)
