### ISSUE TITLE
special chars not working in username

### ISSUE THREAD

**Issue by philippgerard** [hbons/SparkleShare#138] opened 2011-04-20 15:07 UTC
Hi,

it seems that usernames that contain special characters (such as é, è etc.) are not interpreted correctly in RC1. Take a look at this screenshot to see an example: http://cl.ly/440B2k2v2f2k0U1x2Z3I (?? instead of é)

Best,
Philipp

**Comment by bobardkor** [comment] 2015-04-09 07:56
Hi,
This still seems to be a problem, as I have an accented character in my username and it looks garbled: MichaÃ«l in place of Michaël (windows client)
Have you got a solution by any chance? Even if I have to use the unaccented "Michael" - is there a way to edit the client configuration to do this ?

**Comment by hbons** [comment] 2015-04-09 10:26
@bobardkor which version are you using?

**Comment by BarryThePenguin** [comment] 2015-04-09 10:45
Duplicate of #1532?

**Comment by bobardkor** [comment] 2015-04-09 10:47
I'm using the version currently available for download on the main page, seems to be 1.4.0

**Comment by hbons** [comment] 2015-04-10 15:33
@BarryThePenguin yes, it's very well possible this was fixed already. @bobardkor is it possible for you to compile from source to see if that fixes it?

**Closed** 2016-01-26 02:45 UTC
