### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by wideweide** [hbons/SparkleShare#1700] opened 2016-07-01 07:18 UTC
Oops! SparkleShare has crashed... :(

If you want to help fix this crash, please report it at 
https://github.com/hbons/SparkleShare/issues and include the lines below.

Remove any sensitive information like file names, IP addresses, domain names, etc. if needed.

------

SparkleShare version: 1.5.0
Operating system:     Win32NT (Microsoft Windows NT 6.1.7601 Service Pack 1)
System.ArgumentOutOfRangeException: 长度不能小于 0。
参数名: length
   在 System.String.Substring(Int32 startIndex, Int32 length)
   在 SparkleLib.SparkleListenerTcp.<Connect>b__1()
   在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

15:05:47 | ListenerFactory | Issued new listener for tcp://notifications.sparkleshare.org:443/

15:05:47 | Cmd | documents | git config --get filter.bin.clean

15:05:47 | Cmd | documents | git config remote.origin.url "ssh://git@bitbucket.org/***/*ments.git"

15:05:47 | Git | documents | Checking for remote changes...

15:05:47 | S:\SparkleShare\mypentadactyl | Initializing...

15:05:47 | Cmd | documents | git rev-parse HEAD

15:05:47 | Cmd | mypentadactyl | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges

15:05:47 | Cmd | documents | git config core.ignorecase true

15:05:47 | ListenerFactory | Refered to existing listener for tcp://notifications.sparkleshare.org:443/

15:05:47 | Cmd | mypentadactyl | git config core.ignorecase false

15:05:47 | Cmd | documents | git config core.ignorecase false

15:05:47 | Listener | Subscribing to channel 080bb6648e6f933a8599d2e48cba8df44936d484 on tcp://notifications.sparkleshare.org:443/

15:05:47 | Listener | Subscribing to channel 1005071eb09b55005e8b5af80a1df176fa7de7eb on tcp://notifications.sparkleshare.org:443/

15:05:47 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/

15:05:47 | Cmd | mypentadactyl | git config --get filter.bin.clean

15:05:47 | Cmd | documents | git rev-parse --abbrev-ref HEAD

15:05:47 | Cmd | mypentadactyl | git config remote.origin.url "ssh://git@bitbucket.org/***/mypentadactyl"

15:05:47 | Cmd | documents | git ls-remote --heads --exit-code "ssh://git@bitbucket.org/***/documents.git" master

15:05:48 | Git | mypentadactyl | Checking for remote changes...

15:05:48 | Cmd | mypentadactyl | git rev-parse HEAD

15:05:48 | Cmd | mypentadactyl | git config core.ignorecase true

15:05:48 | Cmd | mypentadactyl | git config core.ignorecase false

15:05:48 | Cmd | mypentadactyl | git rev-parse --abbrev-ref HEAD

15:05:48 | Cmd | mypentadactyl | git ls-remote --heads --exit-code "ssh://git@bitbucket.org/***/mypentadactyl" master

**Comment by hbons** [comment] 2016-07-04 07:53
Duplicate of #1699.

**Closed by hbons** 2016-07-04 07:53 UTC
