### ISSUE TITLE
Linux debian package

### ISSUE THREAD

**Issue by ianchanning** [hbons/SparkleShare#1666] opened 2015-11-05 09:25 UTC
Is there any chance of compiling up a debian package for this? Somebody did do this for SparkleShare 1.1 that is in the ubuntu software center but not for the latest edition. Compiling from source on a fresh linux mint machine has taken me two hours and 80+ commands and I still haven't got it installed yet.

**Comment by akuckartz** [comment] 2015-11-06 20:39
:+1:

**Comment by schnip** [comment] 2015-11-16 04:37
I have been having a quite similar problem on my Linux Mint machine. Are you also getting stuck at the step of getting gtk-sharp-3.0 ?

**Comment by ianchanning** [comment] 2015-11-16 11:39
@schnip I can't fully remember - quite possibly yes. In the end I just threw my toys out of the pram and destroyed the vagrant machine I was using. So got rid of any command history.

I've moved my Windows Sparkleshare folder into the vagrant shared folder on a new Mint installation and that does that job well enough.

**Comment by hbons** [comment] 2016-01-26 03:28
Duplicate of #1458.

**Closed by hbons** 2016-01-26 03:28 UTC
