### ISSUE TITLE
[Windows] Crashes if too many updates happens at once

### ISSUE THREAD

**Issue by jordan30001** [hbons/SparkleShare#1762] opened 2017-05-07 10:30 UTC
In a project with a large amount of source files when I build it crashes due to it trying to push all the updates at once (approx 5,000 files).

This problem also occurs when deleting temp files from workspaces if there are enough deletions.

Would it be possible to do multiple smaller pushes instead of one big one?

Log file states the following
11:23:42 | Controller | ssh-agent started, PID=3116
11:23:42 | Environment | SparkleShare version: 1.5.0, Operating system: Win32NT (Microsoft Windows NT 6.2.9200.0)
11:23:42 | Auth | Imported key ''
11:23:42 | Auth | The following keys may be used:
11:23:43 |  | Initializing...
11:23:43 | Cmd | CloudShare | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
11:23:44 | Cmd | CloudShare | git config core.ignorecase false
11:23:44 | ListenerFactory | Issued new listener for tcp://notifications.sparkleshare.org:443/
11:23:44 | Listener | Subscribing to channel  on tcp://notifications.sparkleshare.org:443/
11:23:44 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
11:23:44 | Cmd | CloudShare | git config --get filter.bin.clean
11:23:45 | Cmd | CloudShare | git config remote.origin.url ""
11:23:45 | Git | CloudShare | Checking for remote changes...
11:23:45 | Cmd | CloudShare | git rev-parse HEAD
11:23:45 | Cmd | CloudShare | git config core.ignorecase true
11:23:45 | Cmd | CloudShare | git config core.ignorecase false
11:23:45 | Cmd | CloudShare | git rev-parse --abbrev-ref HEAD
11:23:45 | Cmd | CloudShare | git ls-remote --heads --exit-code "" master
11:23:45 | Git | CloudShare | No remote changes, local+remote: 
11:23:45 | SyncUp | CloudShare | Initiated
11:23:45 | Cmd | CloudShare | git add --all
11:23:50 | Cmd | CloudShare | git status --porcelain
11:23:52 | Cmd | CloudShare | git config user.name ""
11:23:52 | Cmd | CloudShare | git config user.email ""
11:23:52 | Cmd | CloudShare | git commit --all --message="+ 
**_(removed filenames for privacy, but this command contains 550,000 characters
" --author=""_**
11:23:52 | Cmd | Couldn't execute command: The filename or extension is too long

**Comment by edgarborja** [comment] 2017-05-18 00:15
IMHO this is a duplicate of #1635

**Comment by hbons** [comment] 2017-08-28 10:32
Looks like it is the same. Thanks for reporting though!

**Closed by hbons** 2017-08-28 10:32 UTC
