### ISSUE TITLE
High resolution displays problem

### ISSUE THREAD

**Issue by jubalh** [hbons/SparkleShare#1613] opened 2015-02-11 14:42 UTC
I am on a Macbook Retina running Gnome3.
It seems Sparkleshare has problems with high resolution displays. The window size seems to be fixed but since fonts and icons get scaled up by gnom3 there it not enough room for some things. For example I cant select a host service from the window. Going to add a screenshot in here.

![sparkelshot](https://cloud.githubusercontent.com/assets/1658215/6148831/b5e343ea-b204-11e4-95fc-6ce83d2b494d.png)

**Comment by hbons** [comment] 2018-03-11 18:49
I think this has been fixed now that hidpi support in GNOME is more stable. I can't reproduce this in any case, everything scales fine @2x on the latest Fedora.

**Closed by hbons** 2018-03-11 18:49 UTC
Labels: GNOME, bug, up-for-grabs
