### ISSUE TITLE
Errors on quiting SparkleShare on OSX

### ISSUE THREAD

**Issue by markusstoll** [hbons/SparkleShare#1537] opened 2014-07-15 19:17 UTC
After quiting SparkleShare on OSX (using the Quit function in the menulet) sometimes I get this message in an endless loop:

failed to suspend thread 0xb1107000, hopefully it is dead

Are background threads terminated properly before
            Environment.Exit (0);
is called?

**Comment by hbons** [comment] 2015-01-13 21:48
duplicate of #1601.

**Closed by hbons** 2015-01-13 21:48 UTC
Labels: bug, Mac
