### ISSUE TITLE
V1.5 download link for windows

### ISSUE THREAD

**Issue by Addy771** [hbons/SparkleShare#1730] opened 2016-10-04 21:19 UTC
Hello and thank you for your hard work on this project!

On the https://www.sparkleshare.org/ website, the link for the windows version is still for version 1.4. I noticed on twitter that 1.5 should be out for windows. If I edit the download URL to https://bitbucket.org/hbons/sparkleshare/downloads/sparkleshare-windows-1.5.msi I'm actually able to download version 1.5. Is 1.5 intentionally not offered right now?

**Comment by petmos** [comment] 2016-10-15 21:34
@hbons I'm unsure to use 1.5 for windows because there is no link [https://www.sparkleshare.org/](url).
Is there a special reason why 1.5 for windows is not noticed on the homepage?

**Comment by cknoll** [comment] 2016-11-07 21:44
@hbons I also think it should be linked on the main project page. This would have saved me a great amount of time (see [my comment here](https://github.com/hbons/SparkleShare/issues/1649#issuecomment-258044513)) and would make it easier to recommend the project.

**Comment by hbons** [comment] 2017-12-16 22:20
Duplicate of #1781.

**Closed by hbons** 2017-12-16 22:20 UTC

**Comment by petmos** [comment] 2017-12-17 09:17
I still can't find the download link. On https://www.sparkleshare.org you linked to 1.4.
Did you close it because 1.5 no longer relevant or the 1.5 download link is available?

**Comment by hbons** [comment] 2017-12-17 10:47
Closed it as I'm aware of it and the other issue gives more detail on what needs to be done for a new Windows release. :)
