### ISSUE TITLE
SparkleShare fails to open on OS X 10.7

### ISSUE THREAD

**Issue by vote539** [hbons/SparkleShare#1676] opened 2016-01-07 10:24 UTC
I downloaded the release binary from the web site, version 1.5.0.  However, when I attempt to open the app, the app does not open, and the following log appears in Console:

```
1/7/16 4:14:31.900 AM com.apple.launchd.peruser.501: ([0x0-0xa40a4].org.sparkleshare.sparkleshare[2065]) Exited with code: 1
```

The following crash report was saved:

```
Process:         launchd [2261]
Path:            /Applications/SparkleShare.app/Contents/MacOS/SparkleShare
Identifier:      org.sparkleshare.sparkleshare
Version:         ??? (???)
Code Type:       X86 (Native)
Parent Process:  launchd [242]

Date/Time:       2016-01-07 04:20:57.674 -0600
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x000000008fe01030

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x00000000  ebx: 0x00000000  ecx: 0x00000000  edx: 0x00000000
  edi: 0x00000000  esi: 0x00000000  ebp: 0x00000000  esp: 0x00000000
   ss: 0x00000023  efl: 0x00010202  eip: 0x8fe01030   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x00000000
  cr2: 0x8fe01030
Logical CPU: 6

Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 4278
    thread_create: 1
    thread_set_state: 0
```

I also downloaded the project from GitHub, version 1.4.0, and built it using the Debug configuration.  I already had Xamarin Studio version 5.7 installed.  The following log is now produced when launching the app:

```
1/7/16 4:17:01.460 AM [0x0-0xa90a9].org.sparkleshare.sparkleshare: [ERROR] FATAL UNHANDLED EXCEPTION: MonoMac.AppKit.AppKitThreadAccessException: AppKit Consistency error: you are calling a method that can only be invoked from the UI thread.
1/7/16 4:17:01.460 AM [0x0-0xa90a9].org.sparkleshare.sparkleshare:   at MonoMac.AppKit.NSApplication.EnsureUIThread () [0x00000] in <filename unknown>:0 
1/7/16 4:17:01.460 AM [0x0-0xa90a9].org.sparkleshare.sparkleshare:   at MonoMac.AppKit.NSMenu.get_WeakDelegate () [0x00000] in <filename unknown>:0 
1/7/16 4:17:01.460 AM [0x0-0xa90a9].org.sparkleshare.sparkleshare:   at MonoMac.AppKit.NSMenu.get_Delegate () [0x00000] in <filename unknown>:0 
1/7/16 4:17:01.460 AM [0x0-0xa90a9].org.sparkleshare.sparkleshare:   at SparkleShare.SparkleStatusIcon.<SparkleStatusIcon>m__2 (IconState ) [0x00000] in <filename unknown>:0 
1/7/16 4:17:01.460 AM [0x0-0xa90a9].org.sparkleshare.sparkleshare:   at (wrapper delegate-invoke) <Module>:invoke_void_IconState (SparkleShare.IconState)
1/7/16 4:17:01.460 AM [0x0-0xa90a9].org.sparkleshare.sparkleshare:   at SparkleShare.SparkleStatusIconController.<SparkleStatusIconController>m__4 () [0x00000] in <filename unknown>:0 
1/7/16 4:17:01.460 AM [0x0-0xa90a9].org.sparkleshare.sparkleshare:   at (wrapper delegate-invoke) <Module>:invoke_void ()
1/7/16 4:17:01.460 AM [0x0-0xa90a9].org.sparkleshare.sparkleshare:   at SparkleShare.SparkleControllerBase.<UIHasLoaded>m__D () [0x00000] in <filename unknown>:0 
1/7/16 4:17:01.460 AM [0x0-0xa90a9].org.sparkleshare.sparkleshare:   at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 
1/7/16 4:17:01.465 AM com.apple.launchd.peruser.501: ([0x0-0xa90a9].org.sparkleshare.sparkleshare[2255]) Exited with code: 1
```

**Comment by hbons** [comment] 2016-01-26 02:19
Duplicate of #1675.

**Closed by hbons** 2016-01-26 02:19 UTC
