### ISSUE TITLE
Crash on Startup after System Update

### ISSUE THREAD

**Issue by jsthomason** [hbons/SparkleShare#1607] opened 2015-01-21 13:52 UTC
These are the packages I updated this AM....

Aptitude 0.6.8.2: log report
Wed, Jan 21 2015 07:07:25 -0500

IMPORTANT: this log only lists intended actions; actions which fail due to
dpkg problems may not be completed.

Will install 38 packages, and remove 4 packages.
281 MB of disk space will be used
===============================================================================
[REMOVE, NOT USED] libdbus-glib2.0-cil:amd64
[REMOVE, NOT USED] libdbus2.0-cil:amd64
[REMOVE, NOT USED] libmono-corlib4.0-cil:amd64
[REMOVE, NOT USED] libwebkitgtk2.0-cil:amd64
[INSTALL, DEPENDENCIES] libdbus-glib1.0-cil:amd64
[INSTALL, DEPENDENCIES] libdbus1.0-cil:amd64
[INSTALL, DEPENDENCIES] libsoup2.4-cil:amd64
[INSTALL, DEPENDENCIES] libwebkitgtk3.0-cil:amd64
[INSTALL, DEPENDENCIES] linux-headers-3.13.0-45:amd64
[INSTALL, DEPENDENCIES] linux-headers-3.13.0-45-generic:amd64
[INSTALL, DEPENDENCIES] linux-image-3.13.0-45-generic:amd64
[INSTALL, DEPENDENCIES] linux-image-extra-3.13.0-45-generic:amd64
[UPGRADE] debugedit:amd64 4.11.1-3 -> 4.11.1-3ubuntu0.1
[UPGRADE] handbrake-gtk:amd64 6759svnppa1~trusty1 -> 6782svnppa1~trusty1
[UPGRADE] libappindicator3-0.1-cil:amd64 12.10.0-1~ppa+trusty0 -> 12.10.0-2~ppa+trusty2
[UPGRADE] libatk3.0-cil:amd64 2.99.2-2ubuntu1 -> 2.99.3-4~ppa+trusty0
[UPGRADE] libcairo1.10-cil:amd64 2.99.2-2ubuntu1 -> 2.99.3-4~ppa+trusty0
[UPGRADE] libevent-2.0-5:amd64 2.0.21-stable-1ubuntu1 -> 2.0.21-stable-1ubuntu1.14.04.1
[UPGRADE] libgdk3.0-cil:amd64 2.99.2-2ubuntu1 -> 2.99.3-4~ppa+trusty0
[UPGRADE] libgio3.0-cil:amd64 2.99.2-2ubuntu1 -> 2.99.3-4~ppa+trusty0
[UPGRADE] libglib3.0-cil:amd64 2.99.2-2ubuntu1 -> 2.99.3-4~ppa+trusty0
[UPGRADE] libgtk3.0-cil:amd64 2.99.2-2ubuntu1 -> 2.99.3-4~ppa+trusty0
[UPGRADE] libnotify3.0-cil:amd64 3.0.0-1 -> 3.0.3-1~ppa+trusty0
[UPGRADE] libpango3.0-cil:amd64 2.99.2-2ubuntu1 -> 2.99.3-4~ppa+trusty0
[UPGRADE] librpm3:amd64 4.11.1-3 -> 4.11.1-3ubuntu0.1
[UPGRADE] librpmbuild3:amd64 4.11.1-3 -> 4.11.1-3ubuntu0.1
[UPGRADE] librpmio3:amd64 4.11.1-3 -> 4.11.1-3ubuntu0.1
[UPGRADE] librpmsign1:amd64 4.11.1-3 -> 4.11.1-3ubuntu0.1
[UPGRADE] libssh-4:amd64 0.6.1-0ubuntu3 -> 0.6.1-0ubuntu3.1
[UPGRADE] linux-generic:amd64 3.13.0.44.51 -> 3.13.0.45.52
[UPGRADE] linux-headers-generic:amd64 3.13.0.44.51 -> 3.13.0.45.52
[UPGRADE] linux-image-generic:amd64 3.13.0.44.51 -> 3.13.0.45.52
[UPGRADE] linux-libc-dev:amd64 3.13.0-44.73 -> 3.13.0-45.74
[UPGRADE] rpm:amd64 4.11.1-3 -> 4.11.1-3ubuntu0.1
[UPGRADE] rpm-common:amd64 4.11.1-3 -> 4.11.1-3ubuntu0.1
[UPGRADE] rpm2cpio:amd64 4.11.1-3 -> 4.11.1-3ubuntu0.1
[UPGRADE] sparkleshare:amd64 1.4-2~ppa+trusty1 -> 1.4-4~ppa+trusty1
[UPGRADE] thunderbird:amd64 1:31.3.0+build1-0ubuntu0.14.04.1 -> 1:31.4.0+build1-0ubuntu0.14.04.1
[UPGRADE] thunderbird-globalmenu:amd64 1:31.3.0+build1-0ubuntu0.14.04.1 -> 1:31.4.0+build1-0ubuntu0.14.04.1
[UPGRADE] thunderbird-gnome-support:amd64 1:31.3.0+build1-0ubuntu0.14.04.1 -> 1:31.4.0+build1-0ubuntu0.14.04.1
[UPGRADE] thunderbird-locale-en:amd64 1:31.3.0+build1-0ubuntu0.14.04.1 -> 1:31.4.0+build1-0ubuntu0.14.04.1
[UPGRADE] thunderbird-locale-en-us:amd64 1:31.3.0+build1-0ubuntu0.14.04.1 -> 1:31.4.0+build1-0ubuntu0.14.04.1
===============================================================================
Log complete.

....I Rebooted, and Sparkleshare crashes on startup...

Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.WebView ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMAttr ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMNode ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMObject ---> System.DllNotFoundException: libwebkitgtksharpglue-1.10.2.so
  at (wrapper managed-to-native) WebKit.DOMObject:webkitsharp_webkit_domobject_get_parentInstance_offset ()
  at WebKit.DOMObject..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.StaticGetterAdapterFrame[GType] (System.Reflection.StaticGetter`1 getter, System.Object obj) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  at GLib.GType.LookupGObjectType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.Object.LookupGType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.GType.op_Explicit (System.Type type) [0x00000] in <filename unknown>:0 
  at WebKit.DOMNode..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.StaticGetterAdapterFrame[GType] (System.Reflection.StaticGetter`1 getter, System.Object obj) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  at GLib.GType.LookupGObjectType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.Object.LookupGType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.GType.op_Explicit (System.Type type) [0x00000] in <filename unknown>:0 
  at WebKit.DOMAttr..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at GtkSharp.WebkitgtkSharp.ObjectManager.Initialize () [0x00000] in <filename unknown>:0 
  at WebKit.WebView..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at SparkleShare.SparkleEventLog..ctor () [0x00000] in <filename unknown>:0 
  at SparkleShare.SparkleUI.ApplicationActivatedDelegate (System.Object sender, System.EventArgs args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <filename unknown>:0 
  at GLib.Signal.ClosureInvokedCB (System.Object o, GLib.ClosureInvokedArgs args) [0x00000] in <filename unknown>:0 
  at GLib.SignalClosure.Invoke (GLib.ClosureInvokedArgs args) [0x00000] in <filename unknown>:0 
  at GLib.SignalClosure.MarshalCallback (IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data) [0x00000] in <filename unknown>:0 
   at GLib.ExceptionManager.RaiseUnhandledException(System.Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.Application.g_application_run(IntPtr , Int32 , IntPtr )
   at GLib.Application.Run(Int32 argc, System.String argv)
   at SparkleShare.SparkleUI.Run()
   at SparkleShare.Program.Main(System.String[] args)

Thank You .... Hope this helps,
John Thomason

**Comment by hbons** [comment] 2015-01-21 18:09
duplicate of #1606.

**Closed by hbons** 2015-01-21 18:09 UTC
