### ISSUE TITLE
Encrypted Share does not accept correct but wrong password

### ISSUE THREAD

**Issue by gerhard-tinned** [hbons/SparkleShare#1649] opened 2015-08-24 20:47 UTC
I had setup a encrypted share. When adding a new client to the share, the client got asked for the Password. While entering the password, the "Continue" was disabled so the password was not accepted. 

The strange thing is after the 3. character the Continue button became active. Out of curiosity i hit the button ending up with a share that had obviously the wrong password set (base64 content shown in files).

Can you explain how it should work? did i understand it correctly that SparkleShare is checking the password on every character entered in the password field? At least the log would indicate something like that...

**Comment by simsong** [comment] 2015-08-26 12:57
The program is enforcing a minimum password length of 3. It is not checking the password at all. The Continue button does not show up when the password is correct, it shows up when the password you typed is 3 or more characters long.

**Comment by gerhard-tinned** [comment] 2015-08-26 19:18
Apearently, the Continue button got enabled at exacty 3 characters and disabled again after typing the 4th character of the password. Could the reason be that it is on Windows 10?

**Comment by gerhard-tinned** [comment] 2015-09-03 06:29
Could anybody verify this on another Windows 10 computer?

**Comment by eNTi** [comment] 2015-09-09 08:20
Windows 7 here: It doesn't accept any password for me no matter the length.

**Comment by BarryThePenguin** [comment] 2015-09-09 08:58
I have Windows 10 installed now, will investigate soon

**Comment by gerhard-tinned** [comment] 2015-09-15 10:28
It gets more and more urgent now. Does anybody have an update for this? 

Thanks for your help ... 

Any idea for a workaround? When i enter the 3 digit password SparkleShare checks it all out. If i would manually edit the configuration and provide the correct password, can i trigger it somehow to re-decrypt all the files?

Any other idea?

**Comment by simsong** [comment] 2015-09-15 10:53
I don't understand your question.

- Are you actually using a 3-digit password?

- There is no way to re-encrypt the files.

- Nor is there a way to change the password.

**Comment by gerhard-tinned** [comment] 2015-09-25 18:29
No, i do not use a 3 digit password. But Sparkle Share only let me enter a 3 digit password. 

So my idea is to enter the 3 character password (which is wrong but i have no joice). Then i remember that the password is somewhere in a file. So i can go there and correct the password. So far so good. 

But when i enter the wrong password at the setup because it only accepts 3 characters passwordss (maybe a Windows 10 issue?) the git repository is checked out and tried to decrypt with the wrong password - so it is unreadable.

When i manually change the password in the config file, how to get Sparkle Share to decrypt all files with the correct password?

Thanks
Gerhard

**Comment by simsong** [comment] 2015-09-25 18:33
I suggest you do another clone, this time with the correct password.

**Comment by gerhard-tinned** [comment] 2015-09-25 18:38
Hahaha, ... you are funny arent you? SparkleShare does not activate the button to clone the Repository unless it is a password that has exactly 3 characters. 

... So how would you suggest i clone it again with the correct password when i have a password that is longer then 3 characters????

**Comment by simsong** [comment] 2015-09-25 20:03
I have not seen the behavior that you describe.


----

**Comment by gerhard-tinned** [comment] 2015-09-25 20:07
Well, that effect is the whole reason for the ticket. 

So back to my question for the work around. Is it possible?? and if, how?

**Comment by gerhard-tinned** [comment] 2015-09-25 20:08
My guess was it is related to Windows 10. But maybe it has a completely different reason ... I dont know.

**Comment by gerhard-tinned** [comment] 2015-09-25 20:09
@eNTi reports it to not work at all at Windows 7 ... maybe the same reason?

**Comment by gerhard-tinned** [comment] 2015-09-25 20:10
Is there maybe any other precondition SparkleShare needs that might cause this issue? .Net framework version? ... anything else?

**Comment by gerhard-tinned** [comment] 2015-09-26 15:06
Any news, ideas, ... anything?

**Comment by simsong** [comment] 2015-09-26 15:24
I don't know. I'm using MacOS and have had no problems. I suspect that you may need to debug this yourself.

**Comment by gerhard-tinned** [comment] 2015-09-26 16:45
I use MacOSX as well without issues. That is my point. 

I assume it is a windows issue. I used the invite files as specified on the SparkleShare documentation to let a friend test the issue on Windows 10 and Windows 7. 

The following procedure ... 
1.) A share with a password has been created. 
2.) A invite file for that share is created.
3.) The invite file is copied to the SparkleShare directory on Windows 10 or 7
4.) Follow the on screen instructions to setup the share until the password screen
5.) Start slowly typing the password, ... 1, 2, 3, 4, 5, 6, ... characters 
--> the next buton does not get active at all this time. 

This has been tested on Windows 10 and Windows 7. A screencast has been made but can not attached here. I will upload it somewhere and link it in an additionall comment.

**Comment by gerhard-tinned** [comment] 2015-09-26 16:53
http://www.filedropper.com/windows10sparklesharepasswordissue

**Comment by gerhard-tinned** [comment] 2015-09-27 17:08
Can maybe anyone provide me with a version that (temporary) disables the feature that allows only passwords with more then 3 characters (which i have anyway)??

**Comment by simsong** [comment] 2015-09-27 17:26
Hi. The previous messages in this thread make it pretty clear that the problem isn't the version — it's that there is a bug on your version of Windows. I suggest that you get out a debugger and trace execution when you provide a password so that you can see what's going wrong, then submit a bugfix.

**Comment by gerhard-tinned** [comment] 2015-09-28 12:23
Can you please provide more detailed instructions as i am not familiar with the debugging ...

**Comment by simsong** [comment] 2015-09-30 01:34
Hi Gerhard,

Sadly, if you are not familiar with using a debugger, then this project is probably beyond your skill level.  If you want to learn how to do this, I recommend downloading the source and trying to compile your own application.

**Comment by gerhard-tinned** [comment] 2015-09-30 12:23
So you are want to say even if Multiple people report issues in Windows 7 and Windows 10 ( @eNTi and me from Windows 7 and Windows 10 in a test VM) with the exact same symptoms, you refuse to care about it. 

Then you say SparkleShare is only a project for .NET developers but nobody else. Anybody without development skills in .NET should just **GO AWAY!**

**Comment by simsong** [comment] 2015-09-30 12:29
Gerhard,

I'm not a member of the SparkleShare development team. However, it's it's an open source, community project. The nice thing about open source software is that you can fix it yourself, or find someone to fix it for you. How much money did you pay for your copy?   How much are you paying for your monthly support contract?

**Comment by eNTi** [comment] 2015-09-30 12:37
> Gerhard, I'm not a member of the SparkleShare development team. However, it's it's an open source, community project. The nice thing about open source software is that you can fix it yourself, or find someone to fix it for you. How much money did you pay for your copy? How much are you paying for your monthly support contract?

would you please drop the elitist bullshit attitude? not everyone who reports a bug or asks for help is a developer. we all know how open source works. stating the obvious just makes you look like a prick.

**Comment by hbons** [comment] 2015-09-30 13:08
Please everyone be respectful of each other and each other's time.
I'm going to delete the comments that aren't constructive to this issue.

If you don't have anything nice to say, just don't say it at all. :)

**Comment by gerhard-tinned** [comment] 2015-09-30 16:06
So then, How do we deal with this issue as it is reported from multiple Users??

**Comment by gerhard-tinned** [comment] 2015-10-02 14:06
I have still 2-3 workstations where SparkleShare is not working because of this issue. And about 15 Workstation i need to setup where the same issue uis expected. Even if there is no real solution, is there maybe a workaround?? 

Is the workaround i suggested possible?

**Comment by BarryThePenguin** [comment] 2015-10-03 00:04
I've just tested this on Windows 10 and it all looks to be working fine. I'd recommend compiling from master if you are able to.

**Comment by gerhard-tinned** [comment] 2015-10-05 08:01
Did you test it on the PC where you compiled it as well? If so, is there maybe something that needs to be installed to get it working? 

If you have the possibility, can you test your build on a VM from modern.ie? They offer ready to use plain Windows VM images (trail licensed) for IE testing. Would be anought to verify it on a reproduceable base, right? I will try to do the same thing with the version from the website ...

**Comment by BarryThePenguin** [comment] 2015-10-05 08:14
You might want to try [Setup.exe](https://github.com/BarryThePenguin/SparkleShare/releases/tag/1.5.0)

It's not an official release, no support

**Comment by gerhard-tinned** [comment] 2015-10-06 13:48
I will try it ... Thanks.

**Comment by gerhard-tinned** [comment] 2015-10-13 22:41
Seems to be working with the version from @BarryThePenguin - Thanks a lot. The Setup seems to show unusual animations - but did not see it myself jet. I plan to try it on my VM as well and report back to you. 

In the meantime, ... Can you tell us what you have changed or done to make it work? - Thanks

**Comment by BarryThePenguin** [comment] 2015-10-13 22:47
Sorry about the animation, that was me playing around. I haven't changed anything relating to the password, it's just what's in master. If you can compile a version from master, that will work too.

@hbons what's needed to create a new release?

**Comment by gerhard-tinned** [comment] 2015-10-14 11:32
Thanks for the details. I will try to setup a env to compile it from master ... thanks.

**Comment by hbons** [comment] 2015-10-15 15:10
@BarryThePenguin I think we're good to go for a release. We've got quite a few important fixes and nice features in master. Can you do the Windows build?

**Comment by gerhard-tinned** [comment] 2015-10-29 20:50
Hi, i tried the 1.5 version from @BarryThePenguin with the funny animation. 

Sadly it did not solve the issue. But during the first deployment stage i have learned something. 

I tried to install on several Win7a nd Win8 PCs. Interesting was that one Win7 PC was acting as expected and accepted the password. While the others did not. So it seems to be not the Windows version as such that caused it. My guess now is some software that is maybe missing on the Win7 PCs that caused it. Or maybe the wrong version of something SparkleShare requires? 

I Will try to investigate but i am not sure if i will be able to find it. Any suggestions where to start looking??

**Comment by BarryThePenguin** [comment] 2015-10-29 22:35
I'll have time this weekend to prepare something. @hbons I'm happy to handle a release. Are you able to setup an [appveyor](http://www.appveyor.com/) instance and connect it to the SparkleShare repository, then add me as a team member? https://ci.appveyor.com/team

**Comment by hbons** [comment] 2015-10-29 23:46
@BarryThePenguin Should be all set!

**Comment by gerhard-tinned** [comment] 2015-10-31 22:37
i have tried to compile as suggested the trunk version myself and test it. While that i have tried a couple of things which i hope help you with this issue. 

1.) I downloaded the "IE11 Windows 7" VM from http://modern.ie
2.) I installed the official 1.4 version from the website
3.) Tried to join a Share that is encrypted. => The password "Continue Button did not enable after 3, 4,  or any more character. So this would be a way to reproduce the issue in a controlled way. :)

4.) I installed the .Net Framework as linked in the description for self building SparkleShare (https://github.com/hbons/SparkleShare/tree/master/SparkleShare/Windows)
5.) I tried to jin the Share again => The password "Continue Button did not enable after 3, 4,  or any more character.

6.) I installed and copied the linked git files.
7.) I tried to build SparkleShare as described => An executable was generated but with errors that cause it not to start. Herer the error message that comes repeatedly.

C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(847,9): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\IEUser\Desktop\SparkleShare-master\SparkleShare\Windows\SparkleShare.csproj]


Any chance the description is outdated or did i do something wrong? Or did i miss anything else which is required??

**Comment by gerhard-tinned** [comment] 2015-11-18 08:22
As it has been a while already, ... Is there any update on my last comment? Any support? 

I followed the instructions to compile SparkleShare client but the resulting executable is not starting!!

**Comment by gerhard-tinned** [comment] 2015-12-02 11:10
Please, can someone help me???

**Comment by Fred688** [comment] 2016-01-05 00:01
I have hit the same issue... (Win 10 / Sparckleshare 1.4)

The debug log has line like the follow as you type a password in:
08:48:37 | Cmd | test-crypto | openssl enc -d -aes-256-cbc -base64 -pass stdin -in "C:\remote\.tmp\test-crypto\.sparkleshare"

If you take this command and run it on a commandline it fails...
(using defaults, openssl is located in the folder: C:\Program Files (x86)\SparkleShare\msysgit\bin)

C:\temp>"c:\Program Files (x86)\SparkleShare\msysgit\bin\openssl.exe" enc -d -aes-256-cbc -base64 -pass stdin -in test.txt
123456
error reading input file

Remove the -d option and it works...(on the command line... no idea how to do so in the code...)

...

**Comment by hbons** [comment] 2016-01-26 03:26
Can you still reproduce this with version 1.5?

**Comment by payalord** [comment] 2016-01-29 18:04
Just installed from the SparkleShare website the windows version 1.4 and got this problem(Win 7), continue button sill disabled, no matter the length of password entered. Will try to compile it from master.

**Comment by payalord** [comment] 2016-01-29 22:12
I compiled **master**. Done everything by "Windows" instructions. And had the same issue that faced @gerhard-tinned here before, looks like application is not even starting. But actually it is starting and after couple seconds closing. That means sparkleshare.exe working fine, but something goes wrong maybe with something else.

So then i discovered that it is issue with Git 1.x and 2.x. The problem is that [Git for Windows 1.x was retired on August 18th, 2015, superseded by Git for Windows 2.x](https://github.com/msysgit/msysgit). And the link "http://msysgit.github.io/" is wrong now, because it is redirecting to Git 2.x page. But SparkleShare using 1.x. I found the correct one here: [msysGit](https://github.com/msysgit/msysgit/releases)

So with Git 1.x i was finally able to compile and create normal working 1.5 version of SparkleShare and windows installer. Installed it and added my git crypted repo without problems, "Continue" button works fine, password accepted.

P.S. everything has been done on Windows 7 Ultimate

**Comment by BarryThePenguin** [comment] 2016-01-29 22:17
Thanks for looking into this @payalord. We'll have an official 1.5 release for windows using git 1.8.5.2 soon

**Closed** 2016-02-01 00:58 UTC

**Comment by cknoll** [comment] 2016-11-03 01:04
I have the same problem on a Win7 Client.

@BarryThePenguin (Jan. 2016)
> We'll have an official 1.5 release for windows using git 1.8.5.2 soon 

Has there already been an 1.5 release for Windows? Maybe I missed it, but on the official Website it has not yet been published. Alternatively, is there a pre-release which does circumvent the problem?

**Comment by payalord** [comment] 2016-11-03 01:55
@cknoll try this one: https://bitbucket.org/hbons/sparkleshare/downloads/sparkleshare-windows-1.5.msi

**Comment by Fred688** [comment] 2016-11-03 22:24
I did find a work-around for this:
Issue is that when creating the encrypted project, a new unencrypted .sparkleshare file is generated.
When sparkle is asking for the password, it is using it to try to decrypt this file ... and since it is not encrypted the decryption never works, so the button stays greyed out...

Solution was to checkout the .sparkleshare file, encrypt it with your chosen password via openssl and then to check it back in.
Once this was done, I could successfully add the share within sparkleshare...

(I haven't tried 1.5 for this... haven't needed to create a new share for a while)

**Comment by cknoll** [comment] 2016-11-07 21:40
@Fred688 As far as I can say this was not the problem in my case. Version 1.5 fixed it. Thanks. It should, however be linked at the main project website.
