### ISSUE TITLE
client crash: System.ArgumentOutOfRangeException: Cannot be negative.

### ISSUE THREAD

**Issue by ahebrank** [hbons/SparkleShare#1699] opened 2016-07-01 00:42 UTC
This is immediately after startup.  Crashfile follows:

```
Oops! SparkleShare has crashed... :(

If you want to help fix this crash, please report it at
https://github.com/hbons/SparkleShare/issues and include the lines below.

Remove any sensitive information like file names, IP addresses, domain names, etc. if needed.

------

SparkleShare version: 1.5.0
Operating system:     MacOSX (Unix 15.5.0.0)
System.ArgumentOutOfRangeException: Cannot be negative.
Parameter name: length
  at System.String.Substring (Int32 startIndex, Int32 length) [0x00000] in <filename unknown>:0
  at SparkleLib.SparkleListenerTcp.<Connect>m__0 () [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
20:34:40 | Cmd | shared | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config --get filter.bin.clean
20:34:40 | Cmd | shared | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config remote.origin.url "ssh://{USERNAME}@{ADDRESS}/home/storage/shared"
20:34:40 | Git | shared | Checking for remote changes...
20:34:40 | Cmd | shared | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" rev-parse HEAD
20:34:40 | /Users/ahebrank/SparkleShare/synapse | Initializing...
20:34:40 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
20:34:40 | Cmd | shared | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config core.ignorecase true
20:34:40 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" log -n 75 --raw --find-renames --date=iso --format=medium --no-color --no-merges
20:34:40 | Cmd | shared | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config core.ignorecase false
20:34:40 | Cmd | shared | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" rev-parse --abbrev-ref HEAD
20:34:40 | Cmd | shared | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" ls-remote --heads --exit-code "{USERNAME}@{ADDRESS}/home/storage/shared" master
20:34:40 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config core.ignorecase false
20:34:40 | ListenerFactory | Refered to existing listener for tcp://notifications.sparkleshare.org:443/
20:34:40 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config --get filter.bin.clean
20:34:40 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config remote.origin.url "ssh://{USERNAME}@{ADDRESS}/home/storage/synapse"
20:34:40 | Git | synapse | Checking for remote changes...
20:34:40 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" rev-parse HEAD
20:34:40 | /Users/ahebrank/SparkleShare/utd-park | Initializing...
20:34:40 | Cmd | utd-park | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
20:34:40 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config core.ignorecase true
20:34:40 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config core.ignorecase false
20:34:40 | Cmd | utd-park | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config core.ignorecase false
20:34:40 | ListenerFactory | Refered to existing listener for tcp://notifications.sparkleshare.org:443/
20:34:40 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" rev-parse --abbrev-ref HEAD
20:34:40 | Cmd | utd-park | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config --get filter.bin.clean
20:34:40 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" ls-remote --heads --exit-code "ssh://{USERNAME}@{ADDRESS}/home/storage/synapse" master
20:34:40 | Cmd | utd-park | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config remote.origin.url "ssh://{USERNAME}@{ADDRESS}/home/storage/utd-park"
20:34:40 | Git | utd-park | Checking for remote changes...
20:34:40 | Cmd | utd-park | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" rev-parse HEAD
20:34:40 | Cmd | utd-park | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config core.ignorecase true
20:34:40 | Cmd | utd-park | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" config core.ignorecase false
20:34:40 | Cmd | utd-park | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" rev-parse --abbrev-ref HEAD
20:34:40 | Cmd | utd-park | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" ls-remote --heads --exit-code "ssh://{USERNAME}@{ADDRESS}/home/storage/utd-park" master
20:34:41 | Git | 202 | No remote changes, local+remote: 16dc418b23230cf464d64403e07f9fecb47783c6
20:34:41 | Git | andy | No remote changes, local+remote: 2dfe0321b6e24e84229dfd58e6e54fb974b5289a
20:34:41 | Listener | Subscribing to channel 5aeb47217a419bd461c81236cde92948683b6cea on tcp://notifications.sparkleshare.org:443/
20:34:41 | Listener | Subscribing to channel ce382caee6702f5774576461c16c198af230c699 on tcp://notifications.sparkleshare.org:443/
20:34:41 | Listener | Subscribing to channel 1cc5be975625d230ced3c6a60aa9cb22ced3ae55 on tcp://notifications.sparkleshare.org:443/
20:34:41 | Listener | Subscribing to channel cace6dda8a24067005264c9f93720a50d6c7f334 on tcp://notifications.sparkleshare.org:443/
20:34:41 | Listener | Subscribing to channel 42e2e755484140757884feec601171dabab1cb32 on tcp://notifications.sparkleshare.org:443/
20:34:41 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
20:34:41 | Cmd | 202 | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
20:34:41 | Cmd | andy | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
20:34:41 | Git | shared | No remote changes, local+remote: dd86a47bdb1487744f844f7e653a1df6c12d4834
20:34:41 | Cmd | shared | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
20:34:41 | Git | synapse | No remote changes, local+remote: 22dcf0c24ce399fb36f29d2b362034c651df5b51
20:34:41 | Cmd | synapse | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
20:34:41 | Git | utd-park | No remote changes, local+remote: c10133038447c94258c0c0c844df13fe903bae21
20:34:41 | Cmd | utd-park | git --exec-path="/Applications/SparkleShare.app/Contents/Resources/git/libexec/git-core" status --porcelain
```

**Comment by orien3243** [comment] 2016-07-01 02:02
I may have a similar problem. My PC crashed and it gets this error after resolving a conflict.

I also can't get access to sparkleshare.org perhaps that has something to do with it? I've seen before in the logs it tries to reach notifications.sparkleshare.org

I only sync 4 folders and I receive a similar error when I remove all of them and add in one. It only starts up when all folders in config.xml are removed. 

`
SparkleShare is not running, removing stale PID file...
Starting SparkleShare... Done.
joedoe47@greatfox-lylat:~/.config/sparkleshare$ 21:53:02 | Auth | Imported key '/home/joedoe47/.config/sparkleshare/2014-12-20_11h22.key'
21:53:02 | Auth | The following keys may be used:
2048 89:3a:c2:bc:95:ab:2c:08:e6:a9:a1:6d:c9:4c:72:a5 /home/joedoe47/.config/sparkleshare/2014-12-20_11h22.key (RSA)
No bp log location saved, using default.
[000:000] Cpu: 6.58.9, x4, 3801Mhz, 7946MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is Gtk2.
[000:000] Using Gtk2 toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.58.9, x4, 3801Mhz, 7946MB
[000:000] Computer model: Not available
[000:002] Warning(optionsfile.cc:30): Load: Could not open file, err=2
[000:002] No bp log location saved, using default.
[000:002] Cpu: 6.58.9, x4, 3801Mhz, 7946MB
[000:002] Computer model: Not available
[000:002] Browser XEmbed support present: 1
[000:002] Browser toolkit is Gtk2.
[000:002] Using Gtk2 toolkit
[000:002] Warning(optionsfile.cc:30): Load: Could not open file, err=2
[000:002] No bp log location saved, using default.
[000:002] Cpu: 6.58.9, x4, 3801Mhz, 7946MB
[000:002] Computer model: Not available
Vector smash protection is enabled.
21:53:02 | /home/joedoe47/SparkleShare/Documents | Initializing...
21:53:02 | Cmd | Documents | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
21:53:02 | Cmd | Documents | git config core.ignorecase false
21:53:02 | Cmd | Documents | git config --get filter.bin.clean
21:53:02 | ListenerFactory | Issued new listener for tcp://notifications.sparkleshare.org:443/
21:53:02 | Cmd | Documents | git config remote.origin.url "ssh://git@git.joepcs.com/joedoe47/Documents.git"
21:53:02 | /home/joedoe47/SparkleShare/Healthygrub | Initializing...
21:53:02 | Cmd | Healthygrub | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
21:53:02 | Git | Documents | Checking for remote changes...
21:53:02 | Cmd | Documents | git rev-parse HEAD
21:53:02 | Cmd | Documents | git rev-parse --abbrev-ref HEAD
21:53:02 | Cmd | Documents | git ls-remote --heads --exit-code "ssh://git@git.joepcs.com/joedoe47/Documents.git" master
21:53:02 | Cmd | Healthygrub | git config core.ignorecase false
21:53:02 | ListenerFactory | Refered to existing listener for tcp://notifications.sparkleshare.org:443/
21:53:02 | Cmd | Healthygrub | git config --get filter.bin.clean
21:53:02 | Cmd | Healthygrub | git config remote.origin.url "ssh://git@git.joepcs.com/joedoe47/Healthygrub.git"
21:53:02 | Git | Healthygrub | Checking for remote changes...
21:53:02 | /home/joedoe47/SparkleShare/portfolio | Initializing...
21:53:02 | Cmd | Healthygrub | git rev-parse HEAD
21:53:02 | Cmd | portfolio | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
21:53:02 | Cmd | Healthygrub | git rev-parse --abbrev-ref HEAD
21:53:02 | Cmd | Healthygrub | git ls-remote --heads --exit-code "ssh://git@git.joepcs.com/joedoe47/Healthygrub.git" master

(SparkleShare:9874): GLib-CRITICAL **: Source ID 33 was not found when attempting to remove it

(SparkleShare:9874): GLib-CRITICAL **: Source ID 30 was not found when attempting to remove it

(SparkleShare:9874): GLib-CRITICAL **: Source ID 34 was not found when attempting to remove it

(SparkleShare:9874): GLib-CRITICAL **: Source ID 36 was not found when attempting to remove it

(SparkleShare:9874): GLib-CRITICAL **: Source ID 31 was not found when attempting to remove it

(SparkleShare:9874): GLib-CRITICAL **: Source ID 9 was not found when attempting to remove it

(SparkleShare:9874): GLib-CRITICAL **: Source ID 43 was not found when attempting to remove it

(SparkleShare:9874): GLib-CRITICAL **: Source ID 32 was not found when attempting to remove it

(SparkleShare:9874): GLib-CRITICAL **: Source ID 12 was not found when attempting to remove it

(SparkleShare:9874): GLib-CRITICAL **: Source ID 42 was not found when attempting to remove it
21:53:02 | ListenerFactory | Refered to existing listener for tcp://notifications.sparkleshare.org:443/
21:53:02 | Cmd | portfolio | git config core.ignorecase false
21:53:02 | Cmd | portfolio | git config --get filter.bin.clean
21:53:02 | Cmd | portfolio | git config remote.origin.url "ssh://git@git.joepcs.com/joedoe47/portfolio.git"
21:53:02 | Git | portfolio | Checking for remote changes...
21:53:02 | /home/joedoe47/SparkleShare/scripts | Initializing...
21:53:02 | Cmd | portfolio | git rev-parse HEAD
21:53:02 | Cmd | scripts | git log --since=1.month --raw --find-renames --date=iso --format=medium --no-color --no-merges
21:53:02 | Cmd | portfolio | git rev-parse --abbrev-ref HEAD
21:53:02 | Cmd | portfolio | git ls-remote --heads --exit-code "ssh://git@git.joepcs.com/joedoe47/portfolio.git" master
21:53:02 | Listener | Subscribing to channel 90718f6390795865c66261a797f917090ea8a26e on tcp://notifications.sparkleshare.org:443/
21:53:02 | Listener | Subscribing to channel 04f25604e2b92558f2ac043b4a417d8227b5d747 on tcp://notifications.sparkleshare.org:443/
21:53:02 | Listener | Subscribing to channel 0508500e19e73f7343cda8caca410ff114f3774d on tcp://notifications.sparkleshare.org:443/
21:53:02 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/
21:53:02 | ListenerFactory | Refered to existing listener for tcp://notifications.sparkleshare.org:443/
21:53:02 | Cmd | scripts | git config core.ignorecase false
21:53:02 | Listener | Subscribing to channel b1cb7511cc55f5b1f933c773fd0849b4722a9b77 on tcp://notifications.sparkleshare.org:443/
21:53:02 | Cmd | scripts | git config --get filter.bin.clean
21:53:02 | Cmd | scripts | git config remote.origin.url "ssh://git@git.joepcs.com/joedoe47/scripts-crypto.git"
21:53:02 | Git | scripts | Checking for remote changes...
21:53:02 | Cmd | scripts | git rev-parse HEAD
21:53:02 | Cmd | scripts | git rev-parse --abbrev-ref HEAD
21:53:02 | Cmd | scripts | git ls-remote --heads --exit-code "ssh://git@git.joepcs.com/joedoe47/scripts-crypto.git" master
21:53:03 | Git | Healthygrub | No remote changes, local+remote: ede569fcac0f30100f549f6675ac3fb2837e57fa
21:53:03 | SyncUp | Healthygrub | Initiated
21:53:03 | Cmd | Healthygrub | git add --all
fatal: Unable to create '/home/joedoe47/SparkleShare/Healthygrub/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
21:53:03 | SyncUp | Healthygrub | Error
21:53:03 | SyncDown | Healthygrub | Initiated
21:53:03 | Cmd | Healthygrub | git rev-parse HEAD
21:53:03 | Cmd | Healthygrub | git fetch --progress "ssh://git@git.joepcs.com/joedoe47/Healthygrub.git" master
21:53:03 | Git | Documents | No remote changes, local+remote: 3ee4367a694da607f0e2bc558ce9e9718c9044c5
21:53:03 | SyncUp | Documents | Initiated
21:53:03 | Cmd | Documents | git add --all
21:53:03 | Cmd | Documents | git status --porcelain
21:53:03 | Cmd | Documents | git push --progress "ssh://git@git.joepcs.com/joedoe47/Documents.git" master

Unhandled Exception:
System.ArgumentOutOfRangeException: Cannot be negative.
Parameter name: length
  at System.String.Substring (Int32 startIndex, Int32 length) [0x00000] in <filename unknown>:0 
  at SparkleLib.SparkleListenerTcp.<Connect>m__9 () [0x00000] in <filename unknown>:0 
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Cannot be negative.
Parameter name: length
  at System.String.Substring (Int32 startIndex, Int32 length) [0x00000] in <filename unknown>:0 
  at SparkleLib.SparkleListenerTcp.<Connect>m__9 () [0x00000] in <filename unknown>:0 
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
`

**Comment by orien3243** [comment] 2016-07-01 02:28
yep. its the domain. Ran a local notification service and it starts up fine.

https://github.com/hbons/SparkleShare/wiki/Notification-service

Just need to wait for the main server to start up again... or just run your own notification service.

**Comment by orien3243** [comment] 2016-07-01 02:48
Yeah just follow the instructions to run your own notification service and it will work just fine.

https://github.com/hbons/SparkleShare/wiki/Notification-service

**Comment by wideweide** [comment] 2016-07-01 07:18
hi @orien3243  How do notification-service in windows? It seems not worked on windows -- https://github.com/travisghansen/fanout/

**Comment by wideweide** [comment] 2016-07-01 07:23
See my issue: https://github.com/hbons/SparkleShare/issues/1700

**Comment by hbons** [comment] 2016-07-10 14:33
Duplicate of #1628.

**Closed by hbons** 2016-07-10 14:33 UTC
