### ISSUE TITLE
SparkleShare doesn't use SSH agent on OSX

### ISSUE THREAD

**Issue by kevincox** [hbons/SparkleShare#1670] opened 2015-11-27 13:47 UTC
Hello, I have been using SparkleShare on my Linux machines with great results. However I can't get it to work on OSX. I am trying to use the SSH agent provided by gpg-agent to authenticate with my Yubikey. This works fine in the terminal but it doesn't work for SparkleShare for some reason.

```sh
% ssh git@bitbucket.org
PTY allocation request failed on channel 0
logged in as kevincox.

You can use git or hg to connect to Bitbucket. Shell access is disabled.
Connection to bitbucket.org closed.
% launchctl setenv SSH_AUTH_SOCK "$SSH_AUTH_SOCK"
% launchctl setenv SSH_AGENT_PID "$SSH_AGENT_PID"
```

After that when I start SparkleShare it creates a keypair for me and when attempting to clone a repo I get the following logs.

```
08:41:10 | Auth | Fingerprint matches
08:41:10 | Cmd | .tmp | git --exec-path="/Users/kevincox/Downloads/SparkleShare.app/Contents/Resources/git/libexec/git-core" clone --progress --no-checkout --depth=1 "ssh://git@bitbucket.org/kevincox/config" "/Users/kevincox/SparkleShare/.tmp/config"
08:41:10 | Fetcher | warning: templates not found /usr/local/git/share/git-core/templates
08:41:14 | Fetcher | Permission denied (publickey).
08:41:14 | Fetcher | fatal: Could not read from remote repository.
08:41:14 | Fetcher | 
08:41:14 | Fetcher | Please make sure you have the correct access rights
08:41:14 | Fetcher | and the repository exists.
08:41:14 | Fetcher | Failed
```

It would be nice if SparkleShare could use the SSH agent to authenticate over SSH.

**Comment by hbons** [comment] 2016-01-26 03:03
SparkleShare uses its own keys in addition to the ones already used by ssh-agent.
What does `ssh-add -L` say?

**Comment by kevincox** [comment] 2016-01-27 00:10
Sorry, I don't have my Mac on me right now but I remember being about to see both the key and my HSM in `ssh-add -L`. However I can't remember if I added the SparkleShare key manually or if it was added automatically.

For the record I don't want to use a SparkleShare key, I want to use only the HSM so that I don't have to worry about leaving keys on the computer, especially without a passphrase. Right now I am manually using git to get around this (while using SparkleShare on my linux boxes) which isn't very convenient.

**Comment by kevincox** [comment] 2016-02-02 22:02
I just tested and I only have my smartcard in my ssh-agent. Although that error might be interesting.

```
ssh-add -L
error fetching identities for protocol 1: agent refused operation
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCexYutOlqkyMlIY5AszFRJWfGu3i6b4M72z0gTj+Ny96SbxvNVfCE9XCshr7fUUggPSNs3i/Jbv9lYs44YHcGWk/rQDj1vMn+9dv0wYdn13OY5HoYOVV/mQHq3IS1o6NSOdzBW0qyo/vY1hFANC4KCxaUlyf3uEvu/4+BMqjPGYbU3Ym3xtmXotq/euS3A+o3f9kWWQZYHp3KtYk5Vw8Q7LerbqAz0Tkr71am0XvpDW+yU9sXfpu1OXndJPussGPeqP5mPX54STokrk4L8xlTnMvAg+scJiRAwMc7n51NgdOgD5pj5ArXsaL+mhIFDUTGB6hYYqdiD1eoRWiQwNdXJ cardno:000603711657
```

**Comment by hbons** [comment] 2016-06-19 16:34
The next version won't use ssh-agent anymore (just one key for SparkleShare) due to possible configuration conflicts, so I'm closing this.

**Closed by hbons** 2016-06-19 16:34 UTC

**Comment by kevincox** [comment] 2016-06-20 02:32
Is there any way I can convince you to change your mind? This change would probably stop me from using SparkleShare (unless I can find a solution).

I use a HSM (yubikey) to log into my git server and I don't want to add extra keys (especially unencrypted keys) to allow SparkleShare to login.

Also if it helps I don't use a Mac anymore so as long as ssh-agent works on Linux I'm happy.

**Comment by hbons** [comment] 2016-06-20 08:35
Sadly no... There are so many edge cases where SparkleShare just stops working due to configuration edge cases that I can't reproduce that I decided to make SparkleShare use its own key and SSH configuration. Right now implementing Github and Git LFS integration are my main priorities and this will be come much easier this way as well.

Totally open to possible solutions to still be compatible with yubikey.

**Comment by hbons** [comment] 2016-06-20 08:38
About the adding of keys to the server: I highly recommend to have a separate restricted account for SparkleShare, so that there isn't any access to anything on the server except for the files already present on the client.

**Comment by kevincox** [comment] 2016-06-20 13:40
IMHO this sounds like a lot of work. Reimplementing PGP smart cards and SSH authentication using them sounds like a lot of work compared to using an SSH agent but I don't really understand the troubles that you are facing with this and that only really solves my use case where as people can have lots of options configured in there SSH agent and personally I wouldn't imagine trying to implement all of those as well.
