### ISSUE TITLE
Startup crash on Ubuntu GNOME

### ISSUE THREAD

**Issue by matt-pielat** [hbons/SparkleShare#1752] opened 2017-03-17 17:32 UTC
SparkleShare crashes on startup. I do not have any other instances running.

```
matt@matthew-pc:~$ sparkleshare start &
[1] 3365
matt@matthew-pc:~$ 18:23:03 | Environment | SparkleShare version: 1.5.0, Operating system: Unix (Unix 4.8.0.41)
18:23:03 | Auth | Imported key '/home/matt/.config/sparkleshare/2017-03-17_17h46.key'
18:23:03 | Auth | The following keys may be used:
4096 SHA256:E6FMc+o2fyNEGnbeKv7HzOJRCn7U9Jy12IzEgpeBzpk /home/matt/.config/sparkleshare/2017-03-17_17h46.key (RSA)

(process:3366): Gtk-CRITICAL **: gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:3366): GLib-GObject-CRITICAL **: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Gtk.Label.gtk_label_new_with_mnemonic (intptr) <0xffffffff>
  at Gtk.Label..ctor (string) <0x001bf>
  at Gtk.Label..ctor () <0x0000f>
  at SparkleShare.SparkleUI..ctor () <0x00153>
  at SparkleShare.Program.Main (string[]) <0x004d3>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

	mono() [0x49ff2f]
	mono() [0x4f390e]
	mono() [0x426c19]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x11630) [0x7ff851b2d630]
	/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2cf129) [0x7ff8479e8129]
	/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x176588) [0x7ff84788f588]
	/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18afb4) [0x7ff8478a3fb4]
	/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1778cc) [0x7ff8478908cc]
	/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18ae9c) [0x7ff8478a3e9c]
	/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x18af34) [0x7ff8478a3f34]
	/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x178232) [0x7ff847891232]
	/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_type_create_instance+0x1cf) [0x7ff84dcbe30f]
	/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x151fb) [0x7ff84dca01fb]
	/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_newv+0x1dd) [0x7ff84dca1c0d]
	/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_new+0x104) [0x7ff84dca23c4]
	/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1932ba) [0x7ff8478ac2ba]
	/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x362e97) [0x7ff847a7be97]
	/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_type_create_instance+0x1cf) [0x7ff84dcbe30f]
	/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x151fb) [0x7ff84dca01fb]
	/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_newv+0x1dd) [0x7ff84dca1c0d]
	/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_new+0x104) [0x7ff84dca23c4]
	/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_label_new_with_mnemonic+0x19) [0x7ff8479278c9]
	[0x40466210]

Debug info from gdb:

[New LWP 3369]
[New LWP 3370]
[New LWP 3381]
[New LWP 3382]
[New LWP 3383]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007ff851b2d04b in __waitpid (pid=3384, stat_loc=0x7ff85266100c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
29	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7ff8526565c0 (LWP 3366) "mono" 0x00007ff851b2d04b in __waitpid (pid=3384, stat_loc=0x7ff85266100c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  2    Thread 0x7ff850bff700 (LWP 3369) "mono" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7ff85134a700 (LWP 3370) "Finalizer" 0x00007ff851b2b9c7 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7ff84e2ff700 (LWP 3381) "mono" 0x00007ff85184cc8d in read () at ../sysdeps/unix/syscall-template.S:84
  5    Thread 0x7ff83c4d7700 (LWP 3382) "gmain" 0x00007ff8518510bd in poll () at ../sysdeps/unix/syscall-template.S:84
  6    Thread 0x7ff83bcd6700 (LWP 3383) "gdbus" 0x00007ff8518510bd in poll () at ../sysdeps/unix/syscall-template.S:84

Thread 6 (Thread 0x7ff83bcd6700 (LWP 3383)):
#0  0x00007ff8518510bd in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ff84d9c19d6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff84d9c1d62 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff84d2324e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ff84d9e9325 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ff851b236ca in start_thread (arg=0x7ff83bcd6700) at pthread_create.c:333
#6  0x00007ff85185d0af in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 5 (Thread 0x7ff83c4d7700 (LWP 3382)):
#0  0x00007ff8518510bd in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ff84d9c19d6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff84d9c1aec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff84d9c1b31 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ff84d9e9325 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ff851b236ca in start_thread (arg=0x7ff83c4d7700) at pthread_create.c:333
#6  0x00007ff85185d0af in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 4 (Thread 0x7ff84e2ff700 (LWP 3381)):
#0  0x00007ff85184cc8d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000004045da35 in ?? ()
#2  0x00007ff840001900 in ?? ()
#3  0x00007ff850c524d0 in ?? ()
#4  0x00007ff850c54198 in ?? ()
#5  0x00007ff850c52400 in ?? ()
#6  0x00007ff850c52228 in ?? ()
#7  0x00007ff840000e00 in ?? ()
#8  0x000000004045d9b0 in ?? ()
#9  0x00007ff84e2fe9d0 in ?? ()
#10 0x00007ff84e2fe910 in ?? ()
#11 0x000000004045d9b0 in ?? ()
#12 0x00007ff850c541b8 in ?? ()
#13 0x000000004045d7f8 in ?? ()
#14 0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7ff85134a700 (LWP 3370)):
#0  0x00007ff851b2b9c7 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x956820, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ff851b2ba74 in __new_sem_wait_slow (sem=0x956820, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007ff851b2bb1a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x0000000000622e06 in mono_sem_wait ()
#5  0x00000000005a5742 in ?? ()
#6  0x0000000000587b2b in ?? ()
#7  0x0000000000629a8c in ?? ()
#8  0x00007ff851b236ca in start_thread (arg=0x7ff85134a700) at pthread_create.c:333
#9  0x00007ff85185d0af in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 2 (Thread 0x7ff850bff700 (LWP 3369)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000005fdcdb in ?? ()
#2  0x00007ff851b236ca in start_thread (arg=0x7ff850bff700) at pthread_create.c:333
#3  0x00007ff85185d0af in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 1 (Thread 0x7ff8526565c0 (LWP 3366)):
#0  0x00007ff851b2d04b in __waitpid (pid=3384, stat_loc=0x7ff85266100c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00000000004a0006 in ?? ()
#2  0x00000000004f390e in ?? ()
#3  0x0000000000426c19 in ?? ()
#4  <signal handler called>
#5  0x00007ff8479e8129 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ff84788f588 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ff8478a3fb4 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ff8478908cc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ff8478a3e9c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ff8478a3f34 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ff847891232 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ff84dcbe30f in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ff84dca01fb in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ff84dca1c0d in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ff84dca23c4 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ff8478ac2ba in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ff847a7be97 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ff84dcbe30f in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ff84dca01fb in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ff84dca1c0d in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ff84dca23c4 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ff8479278c9 in gtk_label_new_with_mnemonic () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x0000000040466210 in ?? ()
#24 0x0000000000000000 in ?? ()

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

^C
[1]+  Done                    sparkleshare start
```

**Comment by hbons** [comment] 2017-03-18 08:22
Are you running on Wayland?

**Comment by matt-pielat** [comment] 2017-03-18 09:25
No, I have X11.

**Comment by hbons** [comment] 2017-03-18 10:17
Duplicate of #1747.

**Closed by hbons** 2017-03-18 10:17 UTC

**Comment by matt-pielat** [comment] 2017-03-19 09:45
It started working somehow. I've only installed Nvidia CUDA Toolkit on my machine lately but I've no idea if that had anything to do with it.

**Comment by hbons** [comment] 2017-03-19 11:42
It's definitely possible. I'll report this to gtk-sharp, because there shouldn't be anything going wrong creating a simple label.
