### ISSUE TITLE
Doesn't sync if folder has a dot in its name on OS X El Capitan

### ISSUE THREAD

**Issue by semencov** [hbons/SparkleShare#1685] opened 2016-04-13 07:53 UTC
The SparkleShare does not sync if there is a dot in the folder's name. I've added a project which name was a domain name with `.com` on the end, but it didn't sync new changes. However, when I did rename the repo to replace the dot like `-com` and added it like new project to the SparkleShare every thing works like it should be.

If confirm, please append the name restriction rules in the wiki.

**Comment by hbons** [comment] 2017-12-16 18:00
I can't reproduce this. it works fine for me on GitHub with a repo called "test.com". This may have been fixed in a newer version.  Feel free to repopen if it doesn't.

**Closed by hbons** 2017-12-16 18:00 UTC
Labels: bug, Mac, up-for-grabs
