### ISSUE TITLE
Status icon missing after upgrade to Linux Mint 18.1 (Ubuntu  Xenia)

### ISSUE THREAD

**Issue by inolil** [hbons/SparkleShare#1751] opened 2017-03-17 11:40 UTC
Hi,
The main icon of Sparkleshare is missing in the status bar (notification area).

Others icon (synching...) are OK.

Sparkleshare version 1.5.0-1

Thank you for your help

**Comment by gerhard-tinned** [comment] 2017-04-04 14:45
+1
I noticed the same!

**Comment by hbons** [comment] 2017-12-17 10:45
Can you try the 2.0 flatpak and see if this still happens?

**Comment by hbons** [comment] 2017-12-18 19:14
Is this the Ubuntu package? That one is compiled with appindicator support. I don't know if Mint supports that.

**Comment by hbons** [comment] 2018-02-27 21:27
Probably a duplicate of #1790. Try the newer flatpak version if you can.

**Closed by hbons** 2018-02-27 21:27 UTC
Labels: Ubuntu, bug
